export { assessDataCompleteness } from './data-completeness.js'
export { assessVesselSuitability } from './vessel-suitability.js'
export { assessRouteWind, calcEffectiveWindUtilizationRatio } from './route-wind.js'
export { matchWapsType } from './waps-matching.js'
export { calculateFuelSaving, calculateCo2Reduction, DEFAULT_EMISSION_FACTORS } from './fuel-saving.js'
export { calculateEconomics } from './capex-opex.js'
export { assessPolicyCompliance } from './policy-compliance.js'
export { assessShippingOperation } from './shipping-operation.js'
export { assessClassRisk } from './class-risk.js'
export { assessStabilityStructure } from './stability-structure.js'
export { calculateOverallScore, runFullAssessment } from './overall-score.js'
